server:
  port: 8088
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: 12345
  mail:
    host: smtp.gmail.com
    port: 587
    username: skillverseexe@gmail.com
    password: fgbxgyghiglzdcou
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  cloud:
    function:
      definition: notificationDelivery;guardianVerificationDelivery;passwordResetOtpDelivery
    stream:
      bindings:
        notificationDelivery-in-0:
          destination: notification-delivery
        guardianVerificationDelivery-in-0:
          destination: guardian-verification-topic
        passwordResetOtpDelivery-in-0:
          destination: password-reset-otp-topic
      kafka:
        binder:
          brokers: localhost:9092

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port-enabled: true
    secure-port-enabled: false
