# Use postgres/example user/password credentials

services:
  payment_command_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"

#  payment_query_db:
#    image: mongo
#    container_name: payment_query_db
#    restart: on-failure:3
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: 12345
#      MONGO_INITDB_DATABASE: payment_db
#    ports:
#      - "27017:27017"
#    healthcheck:
#      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    restart: on-failure:3
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://mongo:12345@payment_query_db:27017/
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
#      ME_CONFIG_BASICAUTH_ENABLED: true
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin123
#    depends_on:
#      payment_query_db:
#        condition: service_healthy

  auth_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5431:5432"

  chatbot_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: chatbot_db
    ports:
      - "5436:5432"

  classroom_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: classroom_db
    ports:
      - "5434:5432"

  content_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: content_db
    ports:
      - "5435:5432"

  mindmap_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: mindmap_db
    ports:
      - "5444:5432"

  notification_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: notification_db
    ports:
      - "5438:5432"

  premium_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: premium_db
    ports:
      - "5433:5432"

  profile_db:
    image: postgres
    restart: on-failure:3
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: profile_db
    ports:
      - "5437:5432"