server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework

app:
  api:
    prefix: /api/v1
  service-prefix:
    auth: /authenticate
    payment: /payment
    premium: /premium
    mindmap: /mindmap
    content: /content
    chatbot: /chatbot
    profile: /profile
    classroom: /classrooms
    media: /media
    document: /document
    retrieval: /retrieval
    rag: /rag

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://127.0.0.1:8081
            profile-service:
              - uri: http://127.0.0.1:8087
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
            response-timeout: 120s
            pool:
              max-connections: 1000
              max-idle-time: 30s
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service #8081
              uri: lb://auth-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.auth}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.auth}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: payment-service #8082
              uri: lb://payment-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.payment}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.payment}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: premium-service #8083
              uri: lb://premium-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.premium}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.premium}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: mindmap-service #8084
              uri: lb://mindmap-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.mindmap}/**"
              filters:
                - name: StripPrefix
                  args:
                    parts: 2

            - id: content-service #8085
              uri: lb://content-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.content}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.content}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: submissions-service #8085
              uri: lb://content-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}/submissions/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}/submissions/(?<segment>.*)"
                    replacement: "/submissions/${segment}"

            - id: quiz-attempts-service #8085
              uri: lb://content-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}/quiz-attempts/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}/quiz-attempts/(?<segment>.*)"
                    replacement: "/quiz-attempts/${segment}"

            - id: chatbot-service #8086
              uri: lb://chatbot-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.chatbot}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.chatbot}/(?<segment>.*)"
                    replacement: "/chatbot/${segment}"

            - id: profile-service #8087
              uri: lb://profile-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.profile}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.profile}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: classroom-service #8094
              uri: lb://classroom-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.classroom}/**"
              filters:
                - name: StripPrefix
                  args:
                    parts: 2

            - id: media-service #8089
              uri: lb://media-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.media}/**"
              filters:
                - name: StripPrefix
                  args:
                    parts: 0

            - id: document-service-root #8091
              uri: lb://document-service
              predicates:
                - name: Path
                  args:
                    pattern: "/api/v1/document"
              filters:
                - name: SetPath
                  args:
                    template: "/api/v1/documents"

            - id: document-service #8091
              uri: lb://document-service
              predicates:
                - name: Path
                  args:
                    pattern: "/api/v1/document/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "/api/v1/document/(?<segment>.*)"
                    replacement: "/api/v1/documents/${segment}"

            - id: retrieval-service #8092
              uri: lb://retrieval-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.retrieval}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.retrieval}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: rag-service #8093
              uri: lb://rag-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}${app.service-prefix.rag}/**"
              filters:
                - name: RewritePath
                  args:
                    regexp: "${app.api.prefix}${app.service-prefix.rag}/(?<segment>.*)"
                    replacement: "/${segment}"

            - id: notification-service #8088
              uri: lb://notification-service
              predicates:
                - name: Path
                  args:
                    pattern: "${app.api.prefix}/notification/**"
              filters:
                - name: StripPrefix
                  args:
                    parts: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
