spring:
  application:
    name: retrieval-service

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 30s

  data:
    elasticsearch:
      uris: http://localhost:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port-enabled: true
    secure-port-enabled: false

logging:
  level:
    com.mss301.retrievalservice: DEBUG
    feign: DEBUG
    com.mss301.retrievalservice.service.EmbeddingClient: DEBUG

elasticsearch:
  host: http://localhost:9200

feign:
  client:
    config:
      embeddingService:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic

server:
  port: 8092

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

embedding:
  client:
    url: https://aiportalapi.stu-platform.live/jpe/v1
    api-key: sk-Z64PdmBB55a3eXZuLcM2zQ
    model: text-embedding-3-small