server:
  port: 8086
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: chatbot-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatbot_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"